default: &default
  adapter: postgresql
  encoding: utf8
  user:
  pool: 5
  host: localhost
test:
  <<: *default
  database: checkout-api-db

production: &production
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *production
  user: <%= ENV.fetch('DATABASE_USER', 'root') %>
  database: <%= ENV.fetch('DATABASE_NAME', 'checkout_api_db') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'password') %>

staging:
  <<: *production

unicorn:
  <<: *production

sandbox:
  <<: *production